"""Přidán is_visible do Order

Revision ID: 1a151360fb3e
Revises: 0bae8986ed1c
Create Date: 2025-03-25 15:47:44.239207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a151360fb3e'
down_revision = '0bae8986ed1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
